[2023-01-27T04:56:42.078+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: fhv_taxi_data_dag.download_ytd_dataset_from_web scheduled__2022-12-01T00:00:00+00:00 [queued]>
[2023-01-27T04:56:42.086+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: fhv_taxi_data_dag.download_ytd_dataset_from_web scheduled__2022-12-01T00:00:00+00:00 [queued]>
[2023-01-27T04:56:42.086+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-01-27T04:56:42.086+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-01-27T04:56:42.086+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-01-27T04:56:42.097+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): download_ytd_dataset_from_web> on 2022-12-01 00:00:00+00:00
[2023-01-27T04:56:42.102+0000] {standard_task_runner.py:55} INFO - Started process 6286 to run task
[2023-01-27T04:56:42.105+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'fhv_taxi_data_dag', 'download_ytd_dataset_from_web', 'scheduled__2022-12-01T00:00:00+00:00', '--job-id', '5675', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag_v1_fhv.py', '--cfg-path', '/tmp/tmphj3p45ss']
[2023-01-27T04:56:42.106+0000] {standard_task_runner.py:83} INFO - Job 5675: Subtask download_ytd_dataset_from_web
[2023-01-27T04:56:42.160+0000] {task_command.py:388} INFO - Running <TaskInstance: fhv_taxi_data_dag.download_ytd_dataset_from_web scheduled__2022-12-01T00:00:00+00:00 [running]> on host 8bc22b99c76b
[2023-01-27T04:56:42.237+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=fhv_taxi_data_dag
AIRFLOW_CTX_TASK_ID=download_ytd_dataset_from_web
AIRFLOW_CTX_EXECUTION_DATE=2022-12-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-01T00:00:00+00:00
[2023-01-27T04:56:42.238+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-01-27T04:56:42.238+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'wget https://github.com/DataTalksClub/nyc-tlc-data/releases/download/fhv/fhv_tripdata_2022-12.csv.gz -O /opt/***/fhv_tripdata_2022-12.csv.gz']
[2023-01-27T04:56:42.250+0000] {subprocess.py:86} INFO - Output:
[2023-01-27T04:56:42.254+0000] {subprocess.py:93} INFO - --2023-01-27 04:56:42--  https://github.com/DataTalksClub/nyc-tlc-data/releases/download/fhv/fhv_tripdata_2022-12.csv.gz
[2023-01-27T04:56:42.267+0000] {subprocess.py:93} INFO - Resolving github.com (github.com)... 140.82.121.4
[2023-01-27T04:56:42.282+0000] {subprocess.py:93} INFO - Connecting to github.com (github.com)|140.82.121.4|:443... connected.
[2023-01-27T04:56:42.622+0000] {subprocess.py:93} INFO - HTTP request sent, awaiting response... 404 Not Found
[2023-01-27T04:56:42.623+0000] {subprocess.py:93} INFO - 2023-01-27 04:56:42 ERROR 404: Not Found.
[2023-01-27T04:56:42.623+0000] {subprocess.py:93} INFO - 
[2023-01-27T04:56:42.625+0000] {subprocess.py:97} INFO - Command exited with return code 8
[2023-01-27T04:56:42.659+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 8.
[2023-01-27T04:56:42.668+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=fhv_taxi_data_dag, task_id=download_ytd_dataset_from_web, execution_date=20221201T000000, start_date=20230127T045642, end_date=20230127T045642
[2023-01-27T04:56:42.690+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 5675 for task download_ytd_dataset_from_web (Bash command failed. The command returned a non-zero exit code 8.; 6286)
[2023-01-27T04:56:42.718+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-01-27T04:56:42.754+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
